trigger:
- master

jobs:
- job: PyTest
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python36:
        python.version: '3.6'
      anndata_dev:
        python.version: '3.7'
        ANNDATA_DEV: yes
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      export MPLBACKEND="agg"
      echo $MPLBACKEND
    displayName: 'Set env'

  - script: |
      python -m pip install --upgrade pip
      pip install pytest-azurepipelines wheel
      pip install .[dev,doc,test,louvain,leiden,magic,scvi,harmony]
    displayName: 'Install dependencies'

  - script: |
      pip install -v git+https://github.com/theislab/anndata
    displayName: 'Install development anndata'
    condition: eq(variables['ANNDATA_DEV'], 'yes')

  - script: |
      pytest --ignore=scanpy/tests/_images
    displayName: 'PyTest'

- job: static_analysis
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python 3.8'

  - script: pip install black docutils
    displayName: 'Install dependencies'

  - script: |
      black . --check --diff
      python -m scanpy.tests.blackdiff 10
    displayName: 'Black'

  - script: rst2html.py --halt=2 README.rst >/dev/null
    displayName: 'rst2html'
